before:
  hooks:
    - go mod tidy

builds:
  - id: gatekeeper
    main: ./cmd/gatekeeper
    binary: gatekeeper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gatekeeper
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - config.yaml.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: TOomaAh
    name: GateKeeper
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## 🛡️ GateKeeper v{{.Version}}

    Security monitoring and IP blocking system.

  footer: |
    **Full Changelog**: https://github.com/TOomaAh/GateKeeper/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    ### Installation

    Download the appropriate binary for your system from the assets below.

    ```bash
    # Extract the archive
    tar -xzf gatekeeper_*_Linux_x86_64.tar.gz

    # Make it executable
    chmod +x gatekeeper

    # Run
    ./gatekeeper -config config.yaml
    ```
